### ISSUE TITLE
Forward declarations of extern "C" functions are not generated correctly

### ISSUE THREAD

**Issue by igrr** [arduino/arduino-builder#126]
Trying to compile the following sketch:

``` c++
extern "C" void test() {
}

void setup() {
  test();
}

void loop() {
}
```

Leads to an error:

```
/Users/igrokhotkov/Documents/Arduino/Bugreports/B1759_ExternC/B1759_ExternC.ino: In function 'void test()':
B1759_ExternC:1: error: previous declaration of 'void test()' with 'C++' linkage
 extern "C" void test() {
      ^
B1759_ExternC:1: error: conflicts with new declaration with 'C' linkage
 extern "C" void test() {
                      ^
exit status 1
previous declaration of 'void test()' with 'C++' linkage
```

arduino-builder output:
[builder_output.txt](https://github.com/arduino/arduino-builder/files/170586/builder_output.txt)

ctags output:
[ctags_output.txt](https://github.com/arduino/arduino-builder/files/170591/ctags_output.txt)
Note that function signature looks correct in ctags output:
`B1759_ExternC.ino  /^extern "C" void test() {$/;"  kind:function   line:1  signature:()    returntype:void`

sketch with prototypes added:

``` c++
#include <Arduino.h>
#line 1
#line 1 "/Users/igrokhotkov/Documents/Arduino/Bugreports/B1759_ExternC/B1759_ExternC.ino"
#line 1 "/Users/igrokhotkov/Documents/Arduino/Bugreports/B1759_ExternC/B1759_ExternC.ino"
void test();
#line 4 "/Users/igrokhotkov/Documents/Arduino/Bugreports/B1759_ExternC/B1759_ExternC.ino"
void setup();
#line 8 "/Users/igrokhotkov/Documents/Arduino/Bugreports/B1759_ExternC/B1759_ExternC.ino"
void loop();
#line 1
extern "C" void test() {
}

void setup() {
  test();
}

void loop() {
}
```

I'm not sure which version of Arduino introduced this issue, but this certainly worked fine in 1.6.5.

Original issue filed in our repository: https://github.com/esp8266/Arduino/issues/1759

**Comment by facchinm** [comment]
Still not completely fixed as reported on #128 (declaration over n lines)
