### ISSUE TITLE
golang.org/x/tools/cmd/vet no longer exists 

### ISSUE THREAD

**Issue by barnabear** [arduino/arduino-builder#137]
Hi,

The README.md says to use the following line ...

go get golang.org/x/tools/cmd/vet

... but this fails because golang.org/x/tools/cmd/vet no longer exists.

I believe this tool now ships by default in distributions of golang (go).

Please could this be reviewed, and the README.md updated as necessary, please.

Thanks,

Barnabear.

**Comment by cmaglie** [comment]
Thanks!
