### ISSUE TITLE
Arduino_IDE_builder.bash is looking for 'arm' branch in this project.  Has it merged?

### ISSUE THREAD

**Issue by usamitysam** [arduino/arduino-builder#160]
Hi,

Arduino_IDE_builder.bash is looking for 'arm' branch in this project.  
https://github.com/ShorTie8/Arduino_IDE

Has 'arm' branch merged?  Should it use Master?

Thanks

**Comment by cmaglie** [comment]
> Has 'arm' branch merged? Should it use Master?

yes the `arm` branch has been merged long time ago.
There is also build for ARM of the Arduino IDE: https://blog.arduino.cc/2016/05/17/discover-the-latest-arduino-build-for-arm-linux/
