### ISSUE TITLE
Incorrect prototype when using constexpr

### ISSUE THREAD

**Issue by Chris--A** [arduino/arduino-builder#170]
Using 1.6.10 IDE compiled a few days ago.

This code requires a manual prototype, otherwise the IDE combines the `constexpr` and `int` causing an undeclared type error.

``` C++
constexpr int test();
constexpr int test() { return 5; }

void setup() {
  Serial.begin(9600);
  Serial.println(test());
}

void loop() {
}
```

**Comment by esorton** [comment]
I can confirm this issue on Windows 10/Arduino IDE 1.6.9 and 1.6.10.

**Comment by matthijskooijman** [comment]
I can reproduce this as well. This seems to be a problem in ctags, which gets the returntype wrong.

    test    /tmp/arduino_modified_sketch_261104/sketch_aug01a.ino   /^constexpr int test() { return 5; }$/;"        kind:function   line:2  signature:()    returntype:constexprint

@igrr, perhaps we could persuade you to have a look at this? I would presume this is as simple as letting ctags know that `constexpr` is a keyword?

**Comment by esorton** [comment]
Adding `constexpr` as a keyword in arduino/arduino-ctags fixed the issue for me.  Created pull request arduino/ctags#11.

**Comment by matthijskooijman** [comment]
Awesome, thanks!

**Comment by facchinm** [comment]
Fixed by merging https://github.com/arduino/ctags/pull/11
