### ISSUE TITLE
Rebuild of core.a, even when none of its .o files have changed

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/arduino-builder#193]
Long ago in Arduino 1.6.5, rebuilding core.a was skipped when all of its .o files were unchanged.  This used to print in the verbose info:

    Using previously compiled file: /tmp/build2611869353429022717.tmp/core.a

On Windows with slower disk drives, this made quite a noticeable speedup.  Hopefully the builder can implement this someday?

**Comment by PaulStoffregen** [comment]
Here's the old Java code which used to perform this function:

https://github.com/arduino/Arduino/blob/1.6.5-r5/arduino-core/src/processing/app/debug/Compiler.java#L1064

**Comment by cmaglie** [comment]
Fixed by #194
