### ISSUE TITLE
Prototypes are not generated

### ISSUE THREAD

**Issue by me21** [arduino/arduino-builder#197]
Looks similar to #68 and #185, but on Arduino 1.6.12.

reproduce by:

* create sketch test.ino
```
void setup() {
// stuff
}

void loop() {
// do things
 myfunction();
}

void myfunction() {
//code
}
```

> test:7: error: 'myfunction' was not declared in this scope

Tried that on esp8266 and arduino cores. Arduino IDE v1.6.12.

**Comment by me21** [comment]
Seems that Arduino does not like non-latin letters in path to sketches folder. Cyrillic in my case. Changing sketch folder path to the one which does not contain cyrillic letters fixed this for me.

Still, I'm keeping this issue open because it's not good to require latin-only paths.

**Comment by facchinm** [comment]
The issue has been solved by https://github.com/arduino/arduino-builder/commit/46410677e92f51aca90fc9a4689f08eee766ff5f , so next IDE version will contain the proper fix. If you want to test the fix, download the latest release from https://github.com/arduino/arduino-builder/releases/tag/1.3.22 and replace both `arduino-builder` and `ctags` with the downloaded ones
