### ISSUE TITLE
Build now failing when using template class.

### ISSUE THREAD

**Issue by Chris--A** [arduino/arduino-builder#206]
Using IDE 1.8.2

After doing up some code for a forum user, I did a test compile. When I came back to my PC, flames were shooting out the CD drive, and the bit bucket under my desk was overflowing with nibbles of 1's.

To solve the issue, I now have to manually add setup and loop prototypes.

```C++
void setup();
void loop();

template< uint16_t nBuffSize >
  class Foo{
    public: 
  
    template< uint16_t N >
      Foo &operator +=( const Foo<N> &ref ){
        //...
        return *this;
    }
};

Foo<64> a;
Foo<32> b;

void setup(){
  a += b;
}

void loop(){}
```

The preprocessor adds the setup and loop prototypes in between:
`template< uint16_t N >` and 
` Foo &operator +=( const Foo<N> &ref ){`
...in the middle of the class.

**Comment by facchinm** [comment]
https://github.com/arduino/arduino-builder/pull/182 should solve it, I'm testing it immediately

**Comment by facchinm** [comment]
unfortunately it doesn't work in this case :slightly_frowning_face: 
_Investigating_

**Comment by facchinm** [comment]
@Chris--A , the "problem" with your code is the return type of  `operator +=` or, more precisely, the fact that there is no space between the ampersand and "operator" word. PR #207 should fix this issue in a sane way (but we should really take a look and refactor the line insertion code)
