### ISSUE TITLE
Incorrect incompatible architecture warning with multiple architectures values

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-builder#208]
Using Arduino IDE 1.8.2 Hourly Build 2017/01/25 04:33 with Windows 7 64 bit

When there are multiple `architectures` values in library.properties the incompatible architecture warning is incorrectly generated.

Steps to reproduce:

1. Install the Arduino **Scheduler** library (can be done via Library Manager).
3. Open the **MultipleBlinks** example file included with the Scheduler library
4. Compile for an AVR board. The architecture warning shown is:
```
WARNING: library Scheduler claims to run on [sam architecture(s) and may be incompatible with your current board which runs on samd] architecture(s).
```
The correct warning would be something like:
```
WARNING: library Scheduler claims to run on [sam,samd] architecture(s) and may be incompatible with your current board which runs on [avr] architecture.
```

**Comment by facchinm** [comment]
The machine output is ok here, the broken part seems to be the square brackets interpretation
`WARNING: library {0} claims to run on {1} architecture(s) and may be incompatible with your current board which runs on {2} architecture(s). ||| [Scheduler [sam samd] [i586]]`
In fact the java part misinterprets the closing bracket (part of the variable string) as the full closing bracket.
A workaround could be something like https://github.com/facchinm/arduino-builder/commit/019d602bb86e3e0c18e70fa593c1d21383a5164f but it's a super dirty hack. @cmaglie should we move the "square to round brackets" routine into `FromJavaToGoSyntax` function or solve it Java-side?
