### ISSUE TITLE
Make the "Using library" output messages a bit more visible

### ISSUE THREAD

**Issue by cmaglie** [arduino/arduino-builder#25]
I'm talking about the:

```
Using library Keyboard at version 1.0.0 in folder: ....
Using library Mouse at version 1.0.0 in folder: ....
Using library HID at version 1.0 in folder: ....
```

displayed when the verbose output is enabled.

Currently those messages appears in the middle of a bunch of gcc command lines, making them barely visible.

![msg](https://cloud.githubusercontent.com/assets/423515/10244292/879932b8-68fe-11e5-805b-dc82e45a0dc7.png)

If it's not possible to put them at the beginning, maybe it's worth printing them at the end with a line of separation from the "bulk" of the build?

**Comment by PaulStoffregen** [comment]
These used to be at the very beginning, and the duplicate messages were at the very end, right before the size info.

**Comment by ffissore** [comment]
Both messages push to the bottom
