### ISSUE TITLE
The tests in the README: directory structure wrong?

### ISSUE THREAD

**Issue by kenneth558** [arduino/arduino-builder#262]
The README should be corrected where it says:

> In order to run the tests, type:
> 
> go test github.com/arduino/arduino-builder/arduino-builder/...
> 
> This runs all tests, ......
> 

I had to remove that last subdirectory in order to show test actions.  Would you correct that line to:

> go test github.com/arduino/arduino-builder/...

or help me understand where I'm not seeing things correctly?

Ubuntu 16.04 CLI

**Comment by facchinm** [comment]
Correct, should be fixed on the README. Would you mind opening a PR so we can merge it? thanks!

**Comment by kolyshkin** [comment]
I believe I just fixed this in https://github.com/arduino/arduino-builder/pull/264 (among the other things)
