### ISSUE TITLE
Missing GPG signatures for 1.4.0 release

### ISSUE THREAD

**Issue by NicoHood** [arduino/arduino-builder#290]
At least not on Github. Where can I find a signed release?

**Comment by cmaglie** [comment]
Sorry, I've added the missing signatures. https://github.com/arduino/arduino-builder/releases/tag/1.4.0

**Comment by NicoHood** [comment]
https://github.com/arduino/arduino-builder/releases/download/1.4.0/arduino-builder-1.4.0.tar.xz is still missing, only the signature, no zip was provided.

**Comment by cmaglie** [comment]
oh wow, looks impossible but the script missed one file :-o
Now is fixed for good :-)

**Comment by cmaglie** [comment]
becuase it's not released yet... it will be in a couple of hours, we are doing the last tests.

**Comment by NicoHood** [comment]
Missing for 1.4.2 as well.

**Comment by NicoHood** [comment]
Still missing..

**Comment by cmaglie** [comment]
Is the source code enough? or do you need also binaries?

**Comment by NicoHood** [comment]
I compile everything from source. But in general it is also a wise idea to sign precompiled binaries.
