### ISSUE TITLE
Stops compiling and throws unrelated errors

### ISSUE THREAD

**Issue by holgerlembke** [arduino/arduino-builder#306]
We were writting some esp8266 related code, nothing special, just basis stuff. All in all around 600 lines.

Adding an unused and empty function
```
void setupSSDP(void) {
}
```
results in an "error: 'File' was not declared in this scope" at an totally unrelated location.

Changing the name to setuPSSDP makes it compile again, changing the part "setup" to anything else makes it compile again.

You can find the stripped down source code at http://www.lembke.eu/basis2.zip, it can be used with board "Arduino Uno".

**Comment by facchinm** [comment]
Hi @holgerlembke ,
this was probably fixed by https://github.com/arduino/arduino-builder/pull/294 , which we didn't integrate yet into any java IDE release.
Would you mind checking if replacing the `arduino-builder` binary with that release solves your issue?

**Comment by holgerlembke** [comment]
Checked. Does not fix.

**Comment by holgerlembke** [comment]
Rechecked, works fine.

(294 + 304)
