### ISSUE TITLE
add #line directive to source files

### ISSUE THREAD

**Issue by slady** [arduino/arduino-builder#323]
When copying sketch source files into the build directory for building, arduino-builder should add #line directives, so the compiler knows the original filename (which can help with error and warning messages and debugging symbols).
Only .ino files are pre-processed in this way now, but the other source files for building (.c, .cpp, .h) should be handled in the same way.

**Comment by per1234** [comment]
Closing as fixed by https://github.com/arduino/arduino-cli/pull/1224. Thanks @slady!
