### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by arnold-b** [arduino/arduino-builder#338]
Hello,

where is some document. 
Where to install ?
How to use it ?
Does it work under Windows ?

Thanks

**Comment by facchinm** [comment]
Hi @arnold-b ,
the builder is included in Arduino IDE; if you want to install it standalone you can grab the binaries from http://downloads.arduino.cc/tools/arduino-builder-windows-1.4.7.zip (in case you are on windows).
The usage is explained in the [readme](https://github.com/arduino/arduino-builder/blob/master/README.md) or using the inline help.
