### ISSUE TITLE
Include sketch directory to include search path 

### ISSUE THREAD

**Issue by luni64** [arduino/arduino-builder#354]
When doing libraries with project scope settings I usually do something like 

config.h:
```c++
#pragma once

#if __has_include("userConfig.h")
    #include "userConfig.h"
#else
    #include "defaultConfig.h"
#endif
```

If the user want's to override the default settings he can copy `defaultConfig.h` to the sketch folder and rename it to `userConfig.h`. Settings will then be read from userConfig.h which works perfectly with platformIO and makefile builds. 

However, looks like the Arduino builder doesn't include the sketch folder in the search path for include files, so this pattern doesn't work with the Arduino IDE. 

Proposal: Include the sketch folder in the search path

**Comment by per1234** [comment]
Thanks for taking the time to submit an issue @luni64. 

I see we already have a prior issue report about this at https://github.com/arduino/Arduino/issues/2547 (which seems to have been considered equivalent to the discussion of an alternative proposal at https://github.com/arduino/arduino-builder/issues/15).

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
