### ISSUE TITLE
Arduino Error : Error Compiling For Board Arduino Uno

### ISSUE THREAD

**Issue by pragyan-srivastava** [arduino/arduino-builder#356]
Arduino: 1.8.13 (Windows 10), Board: "Arduino Uno"

avr-gcc: error: @C:\Windows\TEMP\cceNc5Ku: Invalid argument
avr-gcc: fatal error: no input files

compilation terminated.

lto-wrapper.exe: fatal error: C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/program files (x86)/arduino/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Tech-Pragyan** [comment]
Anyone, Please Help !!
