### ISSUE TITLE
Multiple libraries warning when platform overrides builtin library

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/arduino-builder#37]
The multiple libraries warning is working, but working too much in some cases.

For example, when compiling any Servo library example on Teensy:  (tested with the latest hourly build)

    Multiple libraries were found for "Servo.h"
     Used: /tmp/arduino-nightly/hardware/teensy/avr/libraries/Servo
     Not used: /tmp/arduino-nightly/libraries/Servo

While harmless, this should not be cause to alert (and distract) end users.  It's perfectly normal for other platforms to override libraries like Servo, which contain code only for specific timers on Atmel chips.

The builder does seem to be properly choosing the platform library over the builtin copy, which is good.  Please consider suppressing this warning message for the case where the duplicate was between only 1 copy in the platform folder and 1 copy in the builtin libraries.

Warning message (in red) become much less meaningful to end users if they appear in normal cases that aren't cause for any concern.

**Comment by matthijskooijman** [comment]
#151 changes the way this issue is fixed, since the current fix has some issues. @PaulStoffregen, care to have a look at #151 and see what you think? I think @cmaglie is planning to merge it Real Soon, though.
