### ISSUE TITLE
How to change arduino-builder to arduino-cli in arduino IDE 1.8.19

### ISSUE THREAD

**Issue by brightproject** [arduino/arduino-builder#375]
I use arduino IDE 1.8.19 for code
When I click the checkmark, the code is compiled.
In the IDE settings, I specified the output of details - verbose.
And when compiling the sketch, I see many many lines that begin with the following lines
`C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Admin\AppData\Local\Arduino15\packages -hardware C:\Users\Admin\Documents\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Admin\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Admin\Documents\Arduino\libraries `
Link about arduino builder [arduino-builder](https://github.com/arduino/arduino-builder)
I realized that the program is deprecated, and it is recommended to use the new version of [arduino-cli](https://github.com/arduino/arduino-cli).
But, after reading the branch about [arduino-cli](https://github.com/arduino/arduino-cli), I got completely confused a very complex tool for a not very advanced programmer.
The main problem, I use the arduino IDE and the core from STMicroelectronics to work with stm32 [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32)
Every programmer knows how many times to compile code during debugging and programming.
This is tens of hundreds of times a day.
The problem with the kernel from ST is that it takes a very, very long time to compile for the Windows platform.
About 20-30 sec on 1 non-biggest scketch.
One solution is to switch to Linux, but this option has not yet been considered by me.
Therefore I look towards the command line.
My actions are the following:
1. The Arduino builder is outdated, so I don’t consider it at all, but it is still used when compiling code from the Arduino IDE
2. Use an arduino-cli, but a very complex entry threshold and there are no examples as such. Documentation for advanced programmers. There is little information on the Internet, on YouTube.
3. Use the command line from the CT kernel itself [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32), but it involves the use of Smake and this is also very, very difficult for me.
Tell me to set up the compiler in step 2, i.e. using arduino cli.
Examples and some hints.
I use power shell as command line.
I registered the global path to the arduino-folder where the arduino-cli is located and I can run the arduino-cli from anywhere.
![Скриншот 11-06-2023 13 56 04](https://github.com/arduino/arduino-builder/assets/1788098/cb01ed4c-2489-4633-bfc0-6439a3bf99e0)
But difficulties with setting up the compiler.
I will be glad for any help.

**Comment by per1234** [comment]
Hi @brightproject. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
