### ISSUE TITLE
Issue when compiling for Fysetc F6 v1.3. This is all it output.====> cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin. cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.  exit status 1

### ISSUE THREAD

**Issue by Bnco3DTech** [arduino/arduino-builder#377]
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.
cc1.exe: error: -fno-fat-lto-objects are supported only with linker plugin.

exit status 1

Compilation error: exit status 1

**Comment by per1234** [comment]
Hi . Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the **arduino-builder** project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
