### ISSUE TITLE
Recursion applied to old format & legacy libraries

### ISSUE THREAD

**Issue by PaulStoffregen** [arduino/arduino-builder#41]
Recursion seems to be applied to old & legacy format libraries.  According to the library spec:

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

    For backward compatibility with Arduino 1.0.x, the library author may opt to not place
    source code into a folder called src. In this case the 1.0 library format is applied and the
    source code is searched from the library root folder and the utility folder

Recursion is being used, compiling files in directories other than the main folder and utility.  It might also be finding .c and .cpp files within the examples.

I will create a test case....

**Comment by PaulStoffregen** [comment]
Here is the test case.  This compiles in 1.6.5, but fails on the latest hourly build.

https://github.com/PaulStoffregen/LegacyNorecurseTest

**Comment by ffissore** [comment]
Good catch! Working on it

**Comment by ffissore** [comment]
Fixed. Fix is available with latest hourly build http://www.arduino.cc/en/Main/Software#hourly
