### ISSUE TITLE
Run ctags only once and drop ComparePrototypesFromSourceAndPreprocSource step

### ISSUE THREAD

**Issue by matthijskooijman** [arduino/arduino-builder#52]
Because ctags now runs with --line-directives, the file and line information in the ctags output correctly reflects the original location of a definition. By running ctags only once on the preprocessed source, and using this information to only generate prototypes for functions defined in the sketch's .ino files, it should no longer be needed to run ctags on the unprocessed sketch source as well.

I previously discussed this with @ffissore, this ticket serves as a reminder for him to implement this later.

**Comment by ffissore** [comment]
Working on it

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly

**Comment by matthijskooijman** [comment]
Just (finally) had a look at the commit, it looks good and a lot more clean than the old code :-D
