### ISSUE TITLE
Make at least 10 items in the "Recent" files list in the IDE

### ISSUE THREAD

**Issue by MikeyMoMo** [arduino/arduino-builder#55]
Please make at least 10 items in the "Recent" files list

**Comment by NicoHood** [comment]
This should be moved here:
https://github.com/arduino/Arduino/issues

However I aggree, 10 items dont take that much space compared to the other entries. Also I really exceed the 5 entries with my tests, so this would be really helpful

**Comment by ffissore** [comment]
This issue was moved to arduino/Arduino#4131
