### ISSUE TITLE
"Library can't use both 'src' and 'utility' folders." error doesn't specify which library

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-builder#56]
Note: I had originally reported https://github.com/arduino/arduino-builder/issues/60 in this issue but have now moved it to its own issue.

Arduino IDE 1.6.7 2011/11/10 12:55 with Windows 7 64 bit:
When compiling, the `Library can't use both 'src' and 'utility' folders.` error doesn't specify which library is causing the problem. This error breaks all compilation so the library causing it must be fixed before the IDE can be used.

Edit: I just discovered that if you open Library Manager or Boards Manager the error does state which library is causing the error.

**Comment by per1234** [comment]
http://forum.arduino.cc/index.php?topic=357966.msg2478929#msg2478929
User fixed the error by deleting the SD library included with Arduino IDE 1.6.6. They were able to install the library with Library manager without causing the error to occur again.

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
