### ISSUE TITLE
exec: "{runtime.tools.ctags.path}/ctags": file does not exist

### ISSUE THREAD

**Issue by tomatopipps** [arduino/arduino-builder#58]
When running form the Arduino install folder:

    arduino-builder.exe -hardware "hardware" -tools "hardware\tools" -fqbn "arduino:avr:leonardo" examples\01.Basics\BareMinimum\BareMinimum.ino
Results in the message:

    exec: "{runtime.tools.ctags.path}/ctags": file does not exist

**Comment by ffissore** [comment]
Please double check how the IDE is calling `arduino-builder`. You're missing a `-tools` folder, the one which has `ctags`

**Comment by tomatopipps** [comment]
Oh, ok, I'm dumb. it needed the `tools-builder` folder.
Maybe make the documentation a bit more clear on that?
