### ISSUE TITLE
Add cmdline option to load build settings from file

### ISSUE THREAD

**Issue by wayoda** [arduino/arduino-builder#6]
For cmdline users of the arduino-builder it would be nice to run the tool with custom build settings read from a file. 
```
arduino-builder --pref-file ~/Whereever/my.standard.build.options.json aSketchToCompile
```

BTW: If the properties in the current build.options.json file were delimted with newline `\n` chars, that file would make a good template for custom settings. 

Eberhard

**Comment by ffissore** [comment]
Fixed. Param is `-build-options-file`. IDE hourly is on the way
