### ISSUE TITLE
Incorrect auto prototype generation with function return type const __FlashStringHelper*

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-builder#69]
Using Arduino IDE 1.6.7 2015/11/20 05:49 with Windows 7 64 bit

The automatically generated prototype for function return type `const __FlashStringHelper*` is missing the space between `const` and `__FlashStringHelper*`
```arduino
void setup() {}
void loop() {}

const __FlashStringHelper* test() {
  return F("y");
}
```
error message:
`sketch_nov22a:4: error: 'const__FlashStringHelper' does not name a type`

This problem doesn't occur in Arduino IDE 1.6.5r5

Originally reported at http://forum.arduino.cc/index.php?topic=361074.0

**Comment by ffissore** [comment]
Fixed. Fix will be available in next hourly build http://www.arduino.cc/en/Main/Software#hourly
