### ISSUE TITLE
WARNING: Spurious .git folder in library

### ISSUE THREAD

**Issue by ffissore** [arduino/arduino-builder#70]
_From @hryamzik on November 23, 2015 1:18_

Due to #3237 there shouldn't be such a warning but I do get in in Arduino IDE v1.6.6.

_Copied from original issue: arduino/Arduino#4204_

**Comment by NicoHood** [comment]
I still get this warning for other folders like this:
`WARNING: Spurious .dev folder in 'HID-Project' library`

It would be cool to remove this as well.

**Comment by ffissore** [comment]
The silenced warnings were about SCCS sofware. It's expected that warnings about actual spurious directories are notified

**Comment by ladyada** [comment]
heya @ffissore - could .github also be ignored? its used to store issue templates and (likely in the future) other github configurations and setups, and will get included in the library zip. 

thank you :)

**Comment by ffissore** [comment]
Hi @ladyada sorry you missed the news but I don't work for arduino any more. See [this message](https://groups.google.com/a/arduino.cc/forum/#!msg/developers/YJLX6AZHem4/kpsLef7XBAAJ). My former colleagues @facchinm @cmaglie and @sandeepmistry will take care of your issue

**Comment by ladyada** [comment]
@ffissore apologies for the mixup - and good luck with all your endeavours! :)

**Comment by matthijskooijman** [comment]
@ladyada, I created a PR for that: https://github.com/arduino/arduino-builder/pull/162

Thanks for the suggestion :-)

**Comment by ladyada** [comment]
love it, thanks!
