### ISSUE TITLE
Preprocessor does not find functions for templates

### ISSUE THREAD

**Issue by NicoHood** [arduino/arduino-builder#73]
This is the test sketch:

```cpp
#include "IRLremote.h"

void setup() {}

// Place it above setup() and it wont work
CNecAPI<NecEvent, IRL_PROTEK_ADDRESS> NecAPI;

void loop() {}

void NecEvent(void){}
```

This the error (if the line was placed above setup()):
```
'NecEvent' was not declared in this scope
```

This is the library state I am using. I also marked the lines of the class template, so you can see the declaration.
https://github.com/NicoHood/IRLremote/blob/4de2ef74b027b5b25d70116214197db7e18eb0b0/src/IRL_Nec.hpp#L325-L327

Basically the builder doesnt see the prototype.

**Comment by ffissore** [comment]
That's a know limitation. Preprocessed source will look like
```c++
#include <Arduino.h>
#line 1
#line 1 "/tmp/arduino_70de4485839d66b9c9a055f6b2ceecea/sketch_nov24a.ino"
// Place it above setup() and it wont work
CNecAPI<NecEvent, IRL_PROTEK_ADDRESS> NecAPI;

#line 4 "/tmp/arduino_70de4485839d66b9c9a055f6b2ceecea/sketch_nov24a.ino"
void setup();
#line 6 "/tmp/arduino_70de4485839d66b9c9a055f6b2ceecea/sketch_nov24a.ino"
void loop();
#line 8 "/tmp/arduino_70de4485839d66b9c9a055f6b2ceecea/sketch_nov24a.ino"
void NecEvent(void);
#line 4
void setup() {}

void loop() {}

void NecEvent(void){}
```
arduino-builder is currently unable to understand that that `NecEvent` you put in the template is a function.
See #50 and in particular https://github.com/arduino/arduino-builder/issues/50#issuecomment-155099077
