### ISSUE TITLE
Delete file does not remove it from compiling list

### ISSUE THREAD

**Issue by NicoHood** [arduino/arduino-builder#75]
* Add a file (tab) test.cpp
* Enter `#error`
* compile
* delete tab
* compile again -> error still there
* save
* error gone??

Also weird is, that if you save and then recompile a few times without saving the error appears again. So the file is somewhere still in the temp folder. Tested on linux.

**Comment by ffissore** [comment]
This issue was moved to arduino/Arduino#4233
